# Generated by Django 3.1.6 on 2021-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210209_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
